CREATE TABLE IF NOT EXISTS Users (
    ID SERIAL PRIMARY KEY,
    Username TEXT NOT NULL,
    Email TEXT NOT NULL UNIQUE,
    Password TEXT NOT NULL,
    Role TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Pets (
    ID SERIAL PRIMARY KEY,
    Name TEXT NOT NULL,
    Description TEXT NOT NULL,
    is_booked BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS Donations (
    ID SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES Users(ID) ON DELETE CASCADE,
    donation_type TEXT NOT NULL,
    amount INTEGER NOT NULL CHECK(amount > 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);